# Generated by Django 6.0.6 on 2026-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_match_stage_prediction_is_doubled_prediction_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='draw_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='first_scoring_team',
            field=models.CharField(blank=True, choices=[('HOME', 'Gospodarze'), ('AWAY', 'Goście'), ('NONE', 'Brak bramek')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='goalscorers',
            field=models.TextField(blank=True, help_text='Wpisz nazwiska po przecinku, np. Lewandowski, Messi', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='predicted_first_team',
            field=models.CharField(blank=True, choices=[('HOME', 'Gospodarze'), ('AWAY', 'Goście'), ('NONE', 'Brak bramek')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='predicted_scorer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
