# Generated by Django 6.0.6 on 2026-06-07 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_match_away_odds_match_draw_odds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='tournament.match')),
            ],
        ),
    ]
