# Generated by Django 6.0.6 on 2026-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournament', '0004_match_away_odds_match_draw_odds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='odds_api_event_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
