# Generated by Django 6.0.6 on 2026-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_match_odds_api_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='football_data_match_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
