# Generated by Django 6.0.6 on 2026-06-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_football_data_match_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_player_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('jersey_number', models.CharField(blank=True, max_length=10, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.team')),
            ],
        ),
    ]
