# Generated by Django 6.0.6 on 2026-06-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_teamplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='goalscorers',
        ),
        migrations.AddField(
            model_name='match',
            name='first_scorer',
            field=models.CharField(blank=True, help_text='Wpisz nazwisko zawodnika, który strzelił pierwszą bramkę w meczu', max_length=100, null=True),
        ),
    ]
