# Generated by Django 6.0.6 on 2026-06-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_bonususage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_pl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
