# Generated by Django 6.0.6 on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'W toku'), ('success', 'Zaktualizowano'), ('error', 'Błąd aktualizacji')], default='pending', max_length=20)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
    ]
