# Generated by Django 6.0.6 on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_apisyncstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='final_api_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='last_api_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
